？？？

diff --git a/.github/workflows/Windows.yml b/.github/workflows/Windows.yml
--- a/.github/workflows/Windows.yml
+++ b/.github/workflows/Windows.yml
@@ -46,6 +46,12 @@ jobs:
       # Build your program with the given configuration
       run: cmake --build ${{github.workspace}}/build --config ${{env.BUILD_TYPE}} --verbose
 
+    - name: Run lupdate
+      run: cmake --build ${{github.workspace}}/build --target lupdate_task || echo "lupdate failed, ignoring."
+
+    - name: Run lrelease
+      run: cmake --build ${{github.workspace}}/build --target lrelease_task || echo "lrelease failed, ignoring."
+
     - name: Check dir
       run: tree ${{ github.workspace }}/build
       
@@ -67,4 +73,4 @@ jobs:
         path: ${{github.workspace}}/MusicPlayer_zh_CN.qm
         # The desired behavior if no files are found using the provided path.
 
-          
+
