111

diff --git a/.github/workflows/Windows.yml b/.github/workflows/Windows.yml
--- a/.github/workflows/Windows.yml
+++ b/.github/workflows/Windows.yml
@@ -44,17 +44,14 @@ jobs:
 
     - name: Build
       # Build your program with the given configuration
-      run: cmake --build ${{github.workspace}}/build --config ${{env.BUILD_TYPE}} --verbose || cmake --build ${{github.workspace}}/build --config ${{env.BUILD_TYPE}} --verbose || cmake --build ${{github.workspace}}/build --config ${{env.BUILD_TYPE}} --verbose || echo "ignoring"
-
-    - name: Run lupdate
-      run: cmake --build ${{github.workspace}}/build --target lupdate_task || echo "lupdate failed, ignoring."
-
-    - name: Run lrelease
-      run: cmake --build ${{github.workspace}}/build --target lrelease_task || echo "lrelease failed, ignoring."
+      run: cmake --build ${{github.workspace}}/build --config ${{env.BUILD_TYPE}} || cmake --build ${{github.workspace}}/build --config ${{env.BUILD_TYPE}} || cmake --build ${{github.workspace}}/build --config ${{env.BUILD_TYPE}} || echo "ignoring"
 
     - name: Check dir
-      run: tree ${{ github.workspace }}/build
-      
+      run: ls ${{ github.workspace }}/qt/Qt/6.8.3/msvc2022_64/bin
+
+    - name: Deploy
+      run: ${{ github.workspace }}/qt/Qt/6.8.3/msvc2022_64/bin/windeployqt ${{github.workspace}}/build/MusicPlayer.exe
+
     - name: Upload build
       uses: actions/upload-artifact@v4.6.2
       with:
@@ -64,13 +61,19 @@ jobs:
         path: ${{github.workspace}}/build/
         # The desired behavior if no files are found using the provided path.
 
-    - name: Upload qm file
-      uses: actions/upload-artifact@v4.6.2
-      with:
-        # Artifact name
-        name: Translation file # optional, default is artifact
-        # A file, directory or wildcard pattern that describes what to upload
-        path: ${{github.workspace}}/MusicPlayer_zh_CN.qm
-        # The desired behavior if no files are found using the provided path.
+#    - name: Run lupdate
+#      run: cmake --build ${{github.workspace}}/build --target lupdate_task || echo "lupdate failed, ignoring."
+
+#    - name: Run lrelease
+#      run: cmake --build ${{github.workspace}}/build --target lrelease_task || echo "lrelease failed, ignoring."
+
+    # - name: Upload qm file
+    #   uses: actions/upload-artifact@v4.6.2
+    #   with:
+    #     # Artifact name
+    #     name: Translation file # optional, default is artifact
+    #     # A file, directory or wildcard pattern that describes what to upload
+    #     path: ${{github.workspace}}/MusicPlayer_zh_CN.qm
+    #     # The desired behavior if no files are found using the provided path.
 
 
